---
title: "Fremont Case Safe Fuzzy Match"
author: "Sonya Kalara"
date: "8/4/2021"
output: html_document
---
# Library Install
```{r setup, include=FALSE}

# Download libraries if they aren't already loaded
libs <- c("tidyverse", "readxl", "stringr", "data.table", "janitor", "base", "formattable", "fuzzyjoin")

for (i in libs){
  if( !is.element(i, .packages(all.available = TRUE)) ) {
    install.packages(i)
  }
  library(i,character.only = TRUE)
}
```

# Read in CSVS / Excel
```{r}
needsmatch <- read_csv("fremont_high school.csv")

# reads in second sheet of an excel doc called "salesforce_all_contacts"
# drops any records that have no case_safe_id or no full name
master <- read_excel("salesforce_all_contacts.xlsx", sheet = 2) %>% 
  filter(!is.na(case_safe_id) & !is.na(full_name))
```
# Drop observations that already have matches
```{r}
# creates a subset of "needsmatch" that already have case_safe_ids recorded
# feel free to delete or skip this step if your "needsmatch" document does not have any matched records
needsmatch_w_csid <- needsmatch %>% 
  filter(!is.na(case_safe_id))

# creates a subset of "needsmatch" that do not have case_safe_ids
# deletes the column entitled "case_safe_id"
needsmatch_wo_csid <- needsmatch %>% 
  filter(is.na(case_safe_id)) %>% 
  select(-case_safe_id) %>% 
  filter(!is.na(col1))

# fills in NA values with the word "empty"
needsmatch_wo_csid[is.na(needsmatch_wo_csid)] <- "empty"
```

# Use stringdist package in R to combine the needsmatch and master documents
```{r}
# If the two datasets "needsmatch_wo_csid" and "master" have different names for the column with the information to be fuzzy matched, change the by = c("full_name" = "full_name") to reflect the correct column titles. For example, if the needsmatch had "full_name" and the master had "Full Name", this line would be written: by = c("full_name" = `Full Name`)

# This code will take a long time to run
joined <- stringdist_left_join(needsmatch_wo_csid, master, by = c("full_name" = "full_name"), method = "jaccard", max_dist = 0.5, distance_col = "simil")

# This dataset will select the row in "master" that has the most linguistic similarity to the name in "needsmatch". The smaller the 'simil' column number is, the more similar the two names are.
joined_fil <- joined %>% 
  group_by(full_name.x) %>% 
  mutate(min = min(simil)) %>% 
  filter(min == simil)

# Outputs into csv
write.csv(joined_fil, "finalized_fuzzy_join.csv")
```

